### ISSUE TITLE
Enter to Portal

### ISSUE THREAD

**Issue by GhostMaree** [ossimc82/RotMG-Proxy-Alpha-#2]
enter dungeon portal "Incorrect Portal key"

**Comment by ossimc82** [comment]
I know, I have no idea why I get this, but I'll work on it

**Comment by C453** [comment]
change the host name to that of the entered portal

**Comment by ossimc82** [comment]
# WOT? # @C453

**Comment by ossimc82** [comment]
Fixed with 76a24ef1561ffb31f399238c8f18d7caaa301c9a
